name: Test Issue Creation
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: |
          gh issue create --title "Test $(date)" --body "Hello"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
